version: "3"

services:
  app:
    image: app
    container_name: app-teste
    build: .
    ports:
      - 3000:3000
    command: npm start 
    restart: always
    environment:
      - NODE_ENV=dev
      - JWT_SECRET=MINHA_SENHA_SECRETA
      - PORT=3000
      - SALT=3
      - MONGODB_URL=mongodb://mongo:27017/testa
    links:
      - mongo   
      
  app-queue:
    image: app
    container_name: app-teste-queue
    build: .
    ports:
      - 3010:3010
    command: npm run queue
    restart: always
    links:
      - mongo
      - app
    depends_on:
      - mongo
      - redis   
      - app   

  mongo:
    image: mongo:latest
    container_name: mongoDBTeste
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=teste
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    command: mongod 
    environment:
      - MONGO_URL=mongodb://mongodb:27017

  redis:
    image: redis
    container_name: redisTestee
    command: redis-server
    ports:
      - "6379:6379"


    
